application:
    build: code
    volumes:
        - /var/www:/var/www
    tty: true

db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root

redis:
    image: redis
    command: 'redis-server --appendonly yes'
    volumes:
        - /var/www/redis:/var/lib/redis

php:
    build: php-7-fpm
    volumes_from:
        - application
    links:
        - db
        - redis

nginx-symfony.dev:
    build: nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/symfony.dev/:/var/log/nginx
    environment:
        NGINX_SERVER_NAME: symfony.dev
        NGINX_DOCUMENT_ROOT: /var/www/symfony/web
        NGINX_INDEX_FILE: app.php

nginx-test.dev:
    build: nginx
    ports:
        - 81:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/test.dev/:/var/log/nginx
    environment:
        NGINX_SERVER_NAME: test.dev
        NGINX_DOCUMENT_ROOT: /var/www/test/web
        NGINX_INDEX_FILE: index.php